# Generated by Django 3.0.8 on 2020-07-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uf',
            fields=[
                ('prefixo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='id',
        ),
        migrations.AddField(
            model_name='cidade',
            name='codigo_ibge',
            field=models.CharField(default='09', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cidade',
            name='codito_uf',
            field=models.ForeignKey(default='09', on_delete=django.db.models.deletion.PROTECT, to='cidades.uf'),
            preserve_default=False,
        ),
    ]
