# Generated by Django 3.0.8 on 2020-07-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0006_auto_20200708_1806'),
        ('feriados', '0002_auto_20200708_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriadomunicipal',
            name='codigo',
            field=models.CharField(default='00', max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feraidoestadual',
            name='codigo',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='feraidoestadual',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidades.Uf'),
        ),
    ]
