# Generated by Django 3.0.8 on 2020-07-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0007_auto_20200708_1810'),
        ('feriados', '0003_auto_20200708_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feraidoestadual',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidades.Uf'),
        ),
        migrations.AlterField(
            model_name='feriadomunicipal',
            name='codigo',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
