# Generated by Django 3.0.8 on 2020-07-08 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0008_auto_20200708_1840'),
        ('feriados', '0004_auto_20200708_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeraidoEstadual',
            new_name='FeridoEstadual',
        ),
        migrations.AlterField(
            model_name='feridoestadual',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidades.Uf'),
        ),
    ]
