# Generated by Django 3.0.8 on 2020-07-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0012_auto_20200708_2243'),
        ('feriados', '0008_auto_20200708_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriadoestadual',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cidades.Uf'),
        ),
        migrations.AlterField(
            model_name='feriadomunicipal',
            name='mes_dia',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
